# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binomial_reg <- function(y_r, n_r, burnin = 500L, run = 500L, r0 = 20, mc_draws = 1E4L) {
    .Call('scalableDA_binomial_reg', PACKAGE = 'scalableDA', y_r, n_r, burnin, run, r0, mc_draws)
}

logistic_reg_random_effect <- function(y, X, burnin = 500L, run = 500L, tau = 10, c = 1, mc_draws = 1E4L, da_ver = 1L, sigma2_ini = 0.01, track_r = FALSE, update_sigma2 = FALSE) {
    .Call('scalableDA_logistic_reg_random_effect', PACKAGE = 'scalableDA', y, X, burnin, run, tau, c, mc_draws, da_ver, sigma2_ini, track_r, update_sigma2)
}

logistic_reg <- function(y, X, b, B, burnin = 500L, run = 500L, r0 = 20) {
    .Call('scalableDA_logistic_reg', PACKAGE = 'scalableDA', y, X, b, B, burnin, run, r0)
}

poisson_reg_random_effect <- function(y, X, burnin = 500L, run = 500L, tau = 10, c = 1, da_ver = 1L, max_r = 1000, update_sigma = FALSE) {
    .Call('scalableDA_poisson_reg_random_effect', PACKAGE = 'scalableDA', y, X, burnin, run, tau, c, da_ver, max_r, update_sigma)
}

poisson_reg <- function(y, X, tune = 100L, burnin = 500L, run = 500L, fixR = FALSE, bigR = 20) {
    .Call('scalableDA_poisson_reg', PACKAGE = 'scalableDA', y, X, tune, burnin, run, fixR, bigR)
}

probit_reg_px <- function(y, X, b, B, burnin = 500L, run = 500L, r0 = 20, mc_draws = 1E4L, nu0 = 1) {
    .Call('scalableDA_probit_reg_px', PACKAGE = 'scalableDA', y, X, b, B, burnin, run, r0, mc_draws, nu0)
}

probit_reg <- function(y, X, b, B, burnin = 500L, run = 500L, r0 = 20, mc_draws = 1E4L) {
    .Call('scalableDA_probit_reg', PACKAGE = 'scalableDA', y, X, b, B, burnin, run, r0, mc_draws)
}

rpg <- function(b, c) {
    .Call('scalableDA_rpg', PACKAGE = 'scalableDA', b, c)
}

