# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rpg <- function(b, c) {
    .Call('ImbalancedPG_rpg', PACKAGE = 'ImbalancedPG', b, c)
}

binomial <- function(n, y, b = 0, B = 1000, burnin = 500L, run = 500L, r_ratio = 20) {
    .Call('ImbalancedPG_binomial', PACKAGE = 'ImbalancedPG', n, y, b, B, burnin, run, r_ratio)
}

logit_reg <- function(y, X, b, B, burnin = 500L, run = 500L, r_ratio = 20, mc_draws = 1E4L) {
    .Call('ImbalancedPG_logit_reg', PACKAGE = 'ImbalancedPG', y, X, b, B, burnin, run, r_ratio, mc_draws)
}

