# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rpg <- function(b, c) {
    .Call('ImbalancedPG_rpg', PACKAGE = 'ImbalancedPG', b, c)
}

multinomial <- function(n, y, b = 0, B = 1000, burnin = 500L, run = 500L, r_ratio = 20) {
    .Call('ImbalancedPG_multinomial', PACKAGE = 'ImbalancedPG', n, y, b, B, burnin, run, r_ratio)
}

